runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/CozyDino/WebAndCloudM1.git#f300f8420b40801420f939b3102b05c1d09c361b'
env_variables:
  'ENDPOINTS_SERVICE_NAME': 'tinyinsta-290312.appspot.com'
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.js)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.html)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /hello
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
